/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { LazyLoadingImg as LazyLoadingImg } from './components/lazy-loading-img/lazy-loading-img';

interface HTMLLazyLoadingImgElement extends LazyLoadingImg, HTMLElement {
}
declare var HTMLLazyLoadingImgElement: {
  prototype: HTMLLazyLoadingImgElement;
  new (): HTMLLazyLoadingImgElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "lazy-loading-img": HTMLLazyLoadingImgElement;
  }
  interface ElementTagNameMap {
      "lazy-loading-img": HTMLLazyLoadingImgElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "lazy-loading-img": JSXElements.LazyLoadingImgAttributes;
      }
  }
  namespace JSXElements {
      export interface LazyLoadingImgAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          src?: string,
          alt?: string
      }
  }
}

